services:
  postgres:
    image: postgres:16
    container_name: orderflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orderflow
      POSTGRES_USER: orderflow
      POSTGRES_PASSWORD: orderflow
    volumes:
      - orderflow_pgdata:/var/lib/postgresql/data

volumes:
  orderflow_pgdata: